import { MongoClient } from "mongodb";

const client = new MongoClient("mongodb://localhost:27017"); // Ganti sesuai konfigurasi MongoDB Anda
const foods = [
  // Untuk Defisit Kalori
  {
    name: "Tumis Kangkung",
    category: "nabati",
    calories: 90,
    protein: 4,
    fat: 3,
    carbs: 12,
    serving_size: "1 piring",
    ingredients: ["kangkung", "bawang putih", "cabai", "minyak"],
    preparation: "tumis",
    portion_weight: 150,
    description: "Tumis kangkung dengan rasa gurih dan rendah kalori.",
  },
  {
    name: "Telur Rebus",
    category: "hewani",
    calories: 70,
    protein: 6,
    fat: 5,
    carbs: 1,
    serving_size: "1 butir",
    ingredients: ["telur"],
    preparation: "rebus",
    portion_weight: 50,
    description: "Telur rebus kaya protein untuk menu sehat.",
  },
  {
    name: "Salad Sayur",
    category: "nabati",
    calories: 80,
    protein: 2,
    fat: 4,
    carbs: 10,
    serving_size: "1 mangkuk",
    ingredients: ["selada", "timun", "wortel", "minyak zaitun", "lemon"],
    preparation: "campur",
    portion_weight: 200,
    description: "Salad sayur segar dengan dressing lemon rendah kalori.",
  },
  {
    name: "Ikan Bakar",
    category: "hewani",
    calories: 150,
    protein: 20,
    fat: 6,
    carbs: 2,
    serving_size: "1 potong",
    ingredients: ["ikan", "bumbu rempah", "jeruk nipis"],
    preparation: "panggang",
    portion_weight: 120,
    description: "Ikan bakar lezat dengan rempah-rempah.",
  },
  {
    name: "Sop Ayam",
    category: "hewani",
    calories: 120,
    protein: 15,
    fat: 5,
    carbs: 8,
    serving_size: "1 mangkuk",
    ingredients: ["ayam", "wortel", "kentang", "kaldu ayam"],
    preparation: "rebus",
    portion_weight: 250,
    description: "Sop ayam hangat dan rendah kalori.",
  },
  {
    name: "Oatmeal Pisang",
    category: "nabati",
    calories: 150,
    protein: 5,
    fat: 3,
    carbs: 25,
    serving_size: "1 mangkuk",
    ingredients: ["oat", "pisang", "madu"],
    preparation: "rebus",
    portion_weight: 200,
    description: "Oatmeal sehat dengan pisang dan madu.",
  },
  {
    name: "Tahu Kukus",
    category: "nabati",
    calories: 90,
    protein: 8,
    fat: 4,
    carbs: 6,
    serving_size: "1 potong",
    ingredients: ["tahu", "bawang putih", "daun bawang"],
    preparation: "kukus",
    portion_weight: 100,
    description: "Tahu kukus lembut dengan aroma bawang.",
  },
  {
    name: "Sate Jamur",
    category: "nabati",
    calories: 110,
    protein: 6,
    fat: 4,
    carbs: 12,
    serving_size: "3 tusuk",
    ingredients: ["jamur", "bumbu kacang", "kecap"],
    preparation: "panggang",
    portion_weight: 150,
    description: "Sate jamur panggang rendah kalori.",
  },

  // Untuk Surplus Kalori (Rendah Lemak)
  {
    name: "Nasi Ayam Kecap",
    category: "hewani",
    calories: 400,
    protein: 25,
    fat: 10,
    carbs: 55,
    serving_size: "1 piring",
    ingredients: ["nasi", "ayam", "kecap", "bumbu rempah"],
    preparation: "goreng",
    portion_weight: 300,
    description: "Nasi ayam kecap dengan rasa manis dan gurih.",
  },
  {
    name: "Pasta Ayam",
    category: "hewani",
    calories: 350,
    protein: 20,
    fat: 8,
    carbs: 50,
    serving_size: "1 piring",
    ingredients: ["pasta", "ayam", "saus tomat"],
    preparation: "rebus",
    portion_weight: 250,
    description: "Pasta ayam dengan saus tomat rendah lemak.",
  },
  {
    name: "Smoothie Alpukat",
    category: "nabati",
    calories: 300,
    protein: 5,
    fat: 15,
    carbs: 40,
    serving_size: "1 gelas",
    ingredients: ["alpukat", "susu rendah lemak", "madu"],
    preparation: "blend",
    portion_weight: 250,
    description: "Smoothie alpukat yang creamy dan bergizi.",
  },
  {
    name: "Tempe Goreng",
    category: "nabati",
    calories: 200,
    protein: 10,
    fat: 8,
    carbs: 18,
    serving_size: "1 potong",
    ingredients: ["tempe", "tepung", "minyak"],
    preparation: "goreng",
    portion_weight: 100,
    description: "Tempe goreng renyah yang kaya protein.",
  },
  {
    name: "Sandwich Telur",
    category: "hewani",
    calories: 300,
    protein: 18,
    fat: 10,
    carbs: 35,
    serving_size: "1 buah",
    ingredients: ["roti gandum", "telur", "sayur", "mayones"],
    preparation: "panggang",
    portion_weight: 200,
    description: "Sandwich telur sehat dengan roti gandum.",
  },
  {
    name: "Mie Goreng Telur",
    category: "hewani",
    calories: 400,
    protein: 12,
    fat: 15,
    carbs: 50,
    serving_size: "1 piring",
    ingredients: ["mie", "telur", "sayuran"],
    preparation: "goreng",
    portion_weight: 250,
    description: "Mie goreng telur klasik yang nikmat.",
  },
  {
    name: "Yogurt dengan Granola",
    category: "nabati",
    calories: 250,
    protein: 10,
    fat: 5,
    carbs: 40,
    serving_size: "1 mangkuk",
    ingredients: ["yogurt", "granola", "buah beri"],
    preparation: "campur",
    portion_weight: 150,
    description: "Yogurt rendah lemak dengan granola sehat.",
  },
  {
    name: "Kentang Panggang",
    category: "nabati",
    calories: 150,
    protein: 4,
    fat: 3,
    carbs: 30,
    serving_size: "1 porsi",
    ingredients: ["kentang", "minyak zaitun", "garam"],
    preparation: "panggang",
    portion_weight: 200,
    description: "Kentang panggang yang renyah di luar dan lembut di dalam.",
  },
  {
    name: "Roti Bakar Selai Kacang",
    category: "nabati",
    calories: 300,
    protein: 8,
    fat: 15,
    carbs: 30,
    serving_size: "1 buah",
    ingredients: ["roti", "selai kacang"],
    preparation: "panggang",
    portion_weight: 150,
    description: "Roti bakar dengan selai kacang kaya energi.",
  },
];

const insertFoods = async () => {
  try {
    await client.connect();
    const db = client.db("healthy_food_recommendation");
    const collection = db.collection("foods");

    // Masukkan data baru
    const insertResult = await collection.insertMany(foods);
    console.log(`${insertResult.insertedCount} new foods inserted.`);
  } finally {
    await client.close();
  }
};

insertFoods().catch(console.error);
